### ISSUE TITLE
Build ios-framework  fails, swift version attribute required

### ISSUE THREAD

**Issue by safarri** [LuisThein/apple_maps_flutter#8] opened 2020-08-03 12:28 UTC
**build ios-framework** fails with the error:

" [!] Unable to determine Swift version for the following pods:

    - `apple_maps_flutter` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set
    the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:125:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:39:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:590:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
"

**Comment by alexshikov** [comment] 2020-10-29 14:34
This is still an issue for us.

**Comment by LuisThein** [comment] 2020-10-29 19:09
I'm not able to reproduce this issue. Did you create your Flutter Project using Objective C?

I found this [issue](https://github.com/flutter/flutter/issues/16049) can you please let me know if this fixes your issue?

**Comment by alexshikov** [comment] 2020-10-30 09:14
The problem is: we have to make a fresh build of embedded flutter library every time.

So we do:

```
flutter clean
flutter build ios-framework
```

What actually helped is to add a `ENV['SWIFT_VERSION'] = '5'` to the `.ios/Podfile` but as you probably know, that file is going to be purged with every `flutter clean`.

You can find a simple project with reproduce of the error here: https://github.com/alexshikov/flutter-map-example

Just follow the steps from the README.

**Comment by alexshikov** [comment] 2020-10-30 11:30
@LuisThein maybe simply adding a SWIFT version to the podspec should fix the problem. Another plugin that we use works great: https://github.com/juliuscanute/qr_code_scanner/blob/master/ios/qr_code_scanner.podspec

**Comment by LuisThein** [comment] 2020-11-28 11:14
Sorry for taking so long.<br>
Thank you for the example project! Now I finally understand. This issue seems to only happen when trying to build a Flutter module, which I actually never tested... Anyway, this should be fixed in the next release 👍

**Closed by LuisThein** 2020-11-28 11:14 UTC
